# Generated by Django 5.0.4 on 2024-11-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fl_test',
            fields=[
                ('ID', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField(default=None, verbose_name='DATE')),
                ('TIME', models.TimeField(default=None, verbose_name='TIME')),
                ('FL_IP', models.CharField(default=None, max_length=32, verbose_name='FL_IP')),
                ('MAC_ADDRESS', models.CharField(default=None, max_length=32, verbose_name='MAC_ADDRESS')),
                ('VERSION', models.CharField(default=None, max_length=32, verbose_name='VERSION')),
                ('GPIO_RED', models.CharField(default=None, max_length=32, verbose_name='GPIO_RED')),
                ('GPIO_GREEN', models.CharField(default=None, max_length=32, verbose_name='GPIO_GREEN')),
                ('GPIO_BLUE', models.CharField(default=None, max_length=32, verbose_name='GPIO_BLUE')),
                ('GPIO_LED1', models.CharField(default=None, max_length=32, verbose_name='GPIO_LED1')),
                ('GPIO_LED2', models.CharField(default=None, max_length=32, verbose_name='GPIO_LED2')),
                ('GPIO_LED3', models.CharField(default=None, max_length=32, verbose_name='GPIO_LED3')),
                ('GPIO_LED4', models.CharField(default=None, max_length=32, verbose_name='GPIO_LED4')),
                ('GPIO_POES', models.CharField(default=None, max_length=32, verbose_name='GPIO_POES')),
                ('GPIO_LASER_TOP', models.CharField(default=None, max_length=32, verbose_name='GPIO_LASER_TOP')),
                ('GPIO_LASER_BTM', models.CharField(default=None, max_length=32, verbose_name='GPIO_LASER_BTM')),
                ('GPIO_LASER_T3D', models.CharField(default=None, max_length=32, verbose_name='GPIO_LASER_T3D')),
                ('GPIO_24V_SM', models.CharField(default=None, max_length=32, verbose_name='GPIO_24V_SM')),
                ('TOP_VALUE', models.CharField(default=None, max_length=2048, verbose_name='TOP_VALUE')),
                ('BTM_VALUE', models.CharField(default=None, max_length=2048, verbose_name='BTM_VALUE')),
            ],
        ),
        migrations.CreateModel(
            name='Laser_data',
            fields=[
                ('ID', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField(default=None, verbose_name='DATE')),
                ('TIME', models.TimeField(default=None, verbose_name='TIME')),
                ('MAC_ADDRESS', models.CharField(default=None, max_length=32, verbose_name='MAC_ADDRESS')),
                ('TOP_VALUE', models.CharField(default=None, max_length=2048, verbose_name='TOP_VALUE')),
                ('BTM_VALUE', models.CharField(default=None, max_length=2048, verbose_name='BTM_VALUE')),
            ],
        ),
        migrations.CreateModel(
            name='Voltage_data',
            fields=[
                ('ID', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField(default=None, verbose_name='DATE')),
                ('TIME', models.TimeField(default=None, verbose_name='TIME')),
                ('MAC_ADDRESS', models.CharField(default=None, max_length=32, verbose_name='MAC_ADDRESS')),
                ('voltage5v', models.CharField(default=None, max_length=32, verbose_name='voltage5v')),
                ('voltage3v3', models.CharField(default=None, max_length=32, verbose_name='voltage3v3')),
                ('voltage3d', models.CharField(default=None, max_length=32, verbose_name='voltage3d')),
                ('voltage24s', models.CharField(default=None, max_length=32, verbose_name='voltage24s')),
                ('voltage48', models.CharField(default=None, max_length=32, verbose_name='voltage48')),
                ('voltage24lower', models.CharField(default=None, max_length=32, verbose_name='voltage24lower')),
                ('voltage24upper', models.CharField(default=None, max_length=32, verbose_name='voltage24upper')),
            ],
        ),
    ]
